export const CollisionTag = Object.freeze({
  Default: "default",
  Player: "player",
  MapObject: "mapobject",
  Road: "road",
  EndWall: "endwall",
  BigBossStart: "bigbossstart",
  SoliderBossStart: "soliderbossstart",
  Boss: "boss",
  FinishLine: "finishline",
  SoliderPlayer: "solider:player",
  SoliderEnemy: "solider:enemy",
  HeadWall: "wall",
  BodyWall: "bodywall",
  Jump: "jump",
  SawBlade: "sawblade",
  Barrier: "barrier",
  Key: "key",
  ChibiCat: "chibicat",
  SpikeTunnel: "spiketunnel",
});
