export const ObjectType = Object.freeze({
  NONE: "none",
  ROAD: "ra",
  WALL: "wall",
  ARENA: "arena",
  FINISH_LINE: "finishLine",
  MATH_WALL: "mathWall",
  END_WALL: "endWall",
  JUMP: "jump",
  SAW_BLADE: "sawblade",
  SAW_BLADE_MOVE: "sawblademove",
  THORN: "thorn",
  BARRIER: "TrapBarrie",
  PILLER: "pillar",
  BANANA: "banana",
  ROTATING_OBJECT: "rotating",
  ROTATING_OBJECT_ONE_SIDE: "rotatingOneSide",
  TRAPFLIPL: "Trap_Flip_L",
  KEY: "key",
  CHIBI_CAT: "ChibiCat",
  SPIKE_TUNNEL: "spiketunnel",
  TRAP_THORN: "trapThorn",
});